/*
 * This file is generated by jOOQ.
*/
package models.jooq


import java.lang.Object

import javax.annotation.Generated

import models.jooq.routines.UpdateModifiedColumn

import org.jooq.Configuration
import org.jooq.Field

import scala.Array


/**
 * Convenience access to all stored procedures and functions in workentry_schema
 */
@Generated(
  value = Array(
    "http://www.jooq.org",
    "jOOQ version:3.9.1"
  ),
  comments = "This class is generated by jOOQ"
)
object Routines {

  /**
   * Call <code>workentry_schema.update_modified_column</code>
   */
  def updateModifiedColumn(configuration : Configuration) : Object = {
    val f = new UpdateModifiedColumn()

    f.execute(configuration)
    f.getReturnValue
  }

  /**
   * Get <code>workentry_schema.update_modified_column</code> as a field.
   */
  def updateModifiedColumn() : Field[Object] = {
    val f = new UpdateModifiedColumn

    return f.asField
  }
}
