/**
 * This class is generated by jOOQ
 */
package models.jooq


import java.lang.Long

import javax.annotation.Generated

import org.jooq.Sequence
import org.jooq.impl.SequenceImpl

import scala.Array


/**
 * Convenience access to all sequences in workentry_schema
 */
@Generated(
  value = Array(
    "http://www.jooq.org",
    "jOOQ version:3.8.6"
  ),
  comments = "This class is generated by jOOQ"
)
object Sequences {

  /**
   * The sequence <code>workentry_schema.th_worklog_id_seq</code>
   */
  val TH_WORKLOG_ID_SEQ : Sequence[Long] = new SequenceImpl[Long]("th_worklog_id_seq", WorkentrySchema.WORKENTRY_SCHEMA, org.jooq.impl.SQLDataType.BIGINT.nullable(false))

  /**
   * The sequence <code>workentry_schema.tm_event_type_id_seq</code>
   */
  val TM_EVENT_TYPE_ID_SEQ : Sequence[Long] = new SequenceImpl[Long]("tm_event_type_id_seq", WorkentrySchema.WORKENTRY_SCHEMA, org.jooq.impl.SQLDataType.BIGINT.nullable(false))

  /**
   * The sequence <code>workentry_schema.tm_role_id_seq</code>
   */
  val TM_ROLE_ID_SEQ : Sequence[Long] = new SequenceImpl[Long]("tm_role_id_seq", WorkentrySchema.WORKENTRY_SCHEMA, org.jooq.impl.SQLDataType.BIGINT.nullable(false))

  /**
   * The sequence <code>workentry_schema.tm_user_contract_id_seq</code>
   */
  val TM_USER_CONTRACT_ID_SEQ : Sequence[Long] = new SequenceImpl[Long]("tm_user_contract_id_seq", WorkentrySchema.WORKENTRY_SCHEMA, org.jooq.impl.SQLDataType.BIGINT.nullable(false))

  /**
   * The sequence <code>workentry_schema.tm_user_id_seq</code>
   */
  val TM_USER_ID_SEQ : Sequence[Long] = new SequenceImpl[Long]("tm_user_id_seq", WorkentrySchema.WORKENTRY_SCHEMA, org.jooq.impl.SQLDataType.BIGINT.nullable(false))

  /**
   * The sequence <code>workentry_schema.tw_event_id_seq</code>
   */
  val TW_EVENT_ID_SEQ : Sequence[Long] = new SequenceImpl[Long]("tw_event_id_seq", WorkentrySchema.WORKENTRY_SCHEMA, org.jooq.impl.SQLDataType.BIGINT.nullable(false))

  /**
   * The sequence <code>workentry_schema.tw_news_id_seq</code>
   */
  val TW_NEWS_ID_SEQ : Sequence[Long] = new SequenceImpl[Long]("tw_news_id_seq", WorkentrySchema.WORKENTRY_SCHEMA, org.jooq.impl.SQLDataType.BIGINT.nullable(false))

  /**
   * The sequence <code>workentry_schema.tw_user_role_id_seq</code>
   */
  val TW_USER_ROLE_ID_SEQ : Sequence[Long] = new SequenceImpl[Long]("tw_user_role_id_seq", WorkentrySchema.WORKENTRY_SCHEMA, org.jooq.impl.SQLDataType.BIGINT.nullable(false))

  /**
   * The sequence <code>workentry_schema.tw_worklog_id_seq</code>
   */
  val TW_WORKLOG_ID_SEQ : Sequence[Long] = new SequenceImpl[Long]("tw_worklog_id_seq", WorkentrySchema.WORKENTRY_SCHEMA, org.jooq.impl.SQLDataType.BIGINT.nullable(false))

  /**
   * The sequence <code>workentry_schema.tw_yearly_balance_id_seq</code>
   */
  val TW_YEARLY_BALANCE_ID_SEQ : Sequence[Long] = new SequenceImpl[Long]("tw_yearly_balance_id_seq", WorkentrySchema.WORKENTRY_SCHEMA, org.jooq.impl.SQLDataType.BIGINT.nullable(false))
}
