/*
 * This file is generated by jOOQ.
*/
package models.jooq


import javax.annotation.Generated

import models.jooq.tables.ThWorklog
import models.jooq.tables.TmEventType
import models.jooq.tables.TmRole
import models.jooq.tables.TmUser
import models.jooq.tables.TmUserContract
import models.jooq.tables.TwEvent
import models.jooq.tables.TwNews
import models.jooq.tables.TwUserRole
import models.jooq.tables.TwWorklog
import models.jooq.tables.TwYearlyBalance

import scala.Array


/**
 * Convenience access to all tables in workentry_schema
 */
@Generated(
  value = Array(
    "http://www.jooq.org",
    "jOOQ version:3.9.1"
  ),
  comments = "This class is generated by jOOQ"
)
object Tables {

  /**
   * The table <code>workentry_schema.th_worklog</code>.
   */
  val TH_WORKLOG = models.jooq.tables.ThWorklog.TH_WORKLOG

  /**
   * The table <code>workentry_schema.tm_event_type</code>.
   */
  val TM_EVENT_TYPE = models.jooq.tables.TmEventType.TM_EVENT_TYPE

  /**
   * The table <code>workentry_schema.tm_role</code>.
   */
  val TM_ROLE = models.jooq.tables.TmRole.TM_ROLE

  /**
   * The table <code>workentry_schema.tm_user</code>.
   */
  val TM_USER = models.jooq.tables.TmUser.TM_USER

  /**
   * The table <code>workentry_schema.tm_user_contract</code>.
   */
  val TM_USER_CONTRACT = models.jooq.tables.TmUserContract.TM_USER_CONTRACT

  /**
   * The table <code>workentry_schema.tw_event</code>.
   */
  val TW_EVENT = models.jooq.tables.TwEvent.TW_EVENT

  /**
   * The table <code>workentry_schema.tw_news</code>.
   */
  val TW_NEWS = models.jooq.tables.TwNews.TW_NEWS

  /**
   * The table <code>workentry_schema.tw_user_role</code>.
   */
  val TW_USER_ROLE = models.jooq.tables.TwUserRole.TW_USER_ROLE

  /**
   * The table <code>workentry_schema.tw_worklog</code>.
   */
  val TW_WORKLOG = models.jooq.tables.TwWorklog.TW_WORKLOG

  /**
   * The table <code>workentry_schema.tw_yearly_balance</code>.
   */
  val TW_YEARLY_BALANCE = models.jooq.tables.TwYearlyBalance.TW_YEARLY_BALANCE
}
