/**
 * This class is generated by jOOQ
 */
package models.pojos


import java.io.Serializable
import java.lang.Integer
import java.lang.String
import java.lang.StringBuilder
import java.time.LocalDateTime

import javax.annotation.Generated

import scala.Array


/**
 * This class is generated by jOOQ.
 */
@Generated(
  value = Array(
    "http://www.jooq.org",
    "jOOQ version:3.8.6"
  ),
  comments = "This class is generated by jOOQ"
)
class TmEventType(
    private var id : Integer      
  , private var name : String       
  , private var description : String       
  , private var color : String       
  , private var created : LocalDateTime
  , private var modified : LocalDateTime
) extends Serializable {

  def this() = {
    this(null, null, null, null, null, null)
  }

  def this (value : TmEventType) = {
    this(
        value.id
      , value.name
      , value.description
      , value.color
      , value.created
      , value.modified
    )
  }

  def getId : Integer = {
    this.id
  }

  def setId(id : Integer) : Unit = {
    this.id = id
  }

  def getName : String = {
    this.name
  }

  def setName(name : String) : Unit = {
    this.name = name
  }

  def getDescription : String = {
    this.description
  }

  def setDescription(description : String) : Unit = {
    this.description = description
  }

  def getColor : String = {
    this.color
  }

  def setColor(color : String) : Unit = {
    this.color = color
  }

  def getCreated : LocalDateTime = {
    this.created
  }

  def setCreated(created : LocalDateTime) : Unit = {
    this.created = created
  }

  def getModified : LocalDateTime = {
    this.modified
  }

  def setModified(modified : LocalDateTime) : Unit = {
    this.modified = modified
  }

  override def toString : String = {
    val sb = new StringBuilder("TmEventType (")

    sb.append(id)
    sb.append(", ").append(name)
    sb.append(", ").append(description)
    sb.append(", ").append(color)
    sb.append(", ").append(created)
    sb.append(", ").append(modified)

    sb.append(")");
    return sb.toString
  }
}
