/*
 * This file is generated by jOOQ.
*/
package models.pojos


import java.io.Serializable
import java.lang.Integer
import java.lang.String
import java.lang.StringBuilder
import java.time.LocalDate
import java.time.LocalDateTime

import javax.annotation.Generated

import scala.Array


/**
 * This class is generated by jOOQ.
 */
@Generated(
  value = Array(
    "http://www.jooq.org",
    "jOOQ version:3.9.1"
  ),
  comments = "This class is generated by jOOQ"
)
class TmUserContract(
    private var id : Integer      
  , private var userId : Integer      
  , private var description : String       
  , private var hoursPerWeek : Integer      
  , private var daysPerWeek : Integer      
  , private var startDate : LocalDate    
  , private var endDate : LocalDate    
  , private var created : LocalDateTime
  , private var modified : LocalDateTime
) extends Serializable {

  def this() = {
    this(null, null, null, null, null, null, null, null, null)
  }

  def this (value : TmUserContract) = {
    this(
        value.id
      , value.userId
      , value.description
      , value.hoursPerWeek
      , value.daysPerWeek
      , value.startDate
      , value.endDate
      , value.created
      , value.modified
    )
  }

  def getId : Integer = {
    this.id
  }

  def setId(id : Integer) : Unit = {
    this.id = id
  }

  def getUserId : Integer = {
    this.userId
  }

  def setUserId(userId : Integer) : Unit = {
    this.userId = userId
  }

  def getDescription : String = {
    this.description
  }

  def setDescription(description : String) : Unit = {
    this.description = description
  }

  def getHoursPerWeek : Integer = {
    this.hoursPerWeek
  }

  def setHoursPerWeek(hoursPerWeek : Integer) : Unit = {
    this.hoursPerWeek = hoursPerWeek
  }

  def getDaysPerWeek : Integer = {
    this.daysPerWeek
  }

  def setDaysPerWeek(daysPerWeek : Integer) : Unit = {
    this.daysPerWeek = daysPerWeek
  }

  def getStartDate : LocalDate = {
    this.startDate
  }

  def setStartDate(startDate : LocalDate) : Unit = {
    this.startDate = startDate
  }

  def getEndDate : LocalDate = {
    this.endDate
  }

  def setEndDate(endDate : LocalDate) : Unit = {
    this.endDate = endDate
  }

  def getCreated : LocalDateTime = {
    this.created
  }

  def setCreated(created : LocalDateTime) : Unit = {
    this.created = created
  }

  def getModified : LocalDateTime = {
    this.modified
  }

  def setModified(modified : LocalDateTime) : Unit = {
    this.modified = modified
  }

  override def toString : String = {
    val sb = new StringBuilder("TmUserContract (")

    sb.append(id)
    sb.append(", ").append(userId)
    sb.append(", ").append(description)
    sb.append(", ").append(hoursPerWeek)
    sb.append(", ").append(daysPerWeek)
    sb.append(", ").append(startDate)
    sb.append(", ").append(endDate)
    sb.append(", ").append(created)
    sb.append(", ").append(modified)

    sb.append(")");
    return sb.toString
  }
}
