/**
 * This class is generated by jOOQ
 */
package models.pojos


import java.io.Serializable
import java.lang.Integer
import java.lang.String
import java.lang.StringBuilder
import java.time.LocalDate
import java.time.LocalDateTime

import javax.annotation.Generated

import scala.Array


/**
 * This class is generated by jOOQ.
 */
@Generated(
  value = Array(
    "http://www.jooq.org",
    "jOOQ version:3.8.6"
  ),
  comments = "This class is generated by jOOQ"
)
class TwWorklog(
    private var id : Integer      
  , private var userId : Integer      
  , private var startDate : LocalDate    
  , private var endDate : LocalDate    
  , private var pauseTime : Integer      
  , private var notes : String       
  , private var editingReason : String       
  , private var updateBy : Integer      
  , private var created : LocalDateTime
  , private var modified : LocalDateTime
) extends Serializable {

  def this() = {
    this(null, null, null, null, null, null, null, null, null, null)
  }

  def this (value : TwWorklog) = {
    this(
        value.id
      , value.userId
      , value.startDate
      , value.endDate
      , value.pauseTime
      , value.notes
      , value.editingReason
      , value.updateBy
      , value.created
      , value.modified
    )
  }

  def getId : Integer = {
    this.id
  }

  def setId(id : Integer) : Unit = {
    this.id = id
  }

  def getUserId : Integer = {
    this.userId
  }

  def setUserId(userId : Integer) : Unit = {
    this.userId = userId
  }

  def getStartDate : LocalDate = {
    this.startDate
  }

  def setStartDate(startDate : LocalDate) : Unit = {
    this.startDate = startDate
  }

  def getEndDate : LocalDate = {
    this.endDate
  }

  def setEndDate(endDate : LocalDate) : Unit = {
    this.endDate = endDate
  }

  def getPauseTime : Integer = {
    this.pauseTime
  }

  def setPauseTime(pauseTime : Integer) : Unit = {
    this.pauseTime = pauseTime
  }

  def getNotes : String = {
    this.notes
  }

  def setNotes(notes : String) : Unit = {
    this.notes = notes
  }

  def getEditingReason : String = {
    this.editingReason
  }

  def setEditingReason(editingReason : String) : Unit = {
    this.editingReason = editingReason
  }

  def getUpdateBy : Integer = {
    this.updateBy
  }

  def setUpdateBy(updateBy : Integer) : Unit = {
    this.updateBy = updateBy
  }

  def getCreated : LocalDateTime = {
    this.created
  }

  def setCreated(created : LocalDateTime) : Unit = {
    this.created = created
  }

  def getModified : LocalDateTime = {
    this.modified
  }

  def setModified(modified : LocalDateTime) : Unit = {
    this.modified = modified
  }

  override def toString : String = {
    val sb = new StringBuilder("TwWorklog (")

    sb.append(id)
    sb.append(", ").append(userId)
    sb.append(", ").append(startDate)
    sb.append(", ").append(endDate)
    sb.append(", ").append(pauseTime)
    sb.append(", ").append(notes)
    sb.append(", ").append(editingReason)
    sb.append(", ").append(updateBy)
    sb.append(", ").append(created)
    sb.append(", ").append(modified)

    sb.append(")");
    return sb.toString
  }
}
