/*
 * This file is generated by jOOQ.
*/
package models.pojos


import java.io.Serializable
import java.lang.Integer
import java.lang.StringBuilder
import java.math.BigDecimal
import java.time.LocalDateTime

import javax.annotation.Generated

import scala.Array


/**
 * This class is generated by jOOQ.
 */
@Generated(
  value = Array(
    "http://www.jooq.org",
    "jOOQ version:3.9.1"
  ),
  comments = "This class is generated by jOOQ"
)
class TwYearlyBalance(
    private var id : Integer      
  , private var userId : Integer      
  , private var year : Integer      
  , private var hourBalance : BigDecimal   
  , private var vacationBalance : BigDecimal   
  , private var created : LocalDateTime
  , private var modified : LocalDateTime
) extends Serializable {

  def this() = {
    this(null, null, null, null, null, null, null)
  }

  def this (value : TwYearlyBalance) = {
    this(
        value.id
      , value.userId
      , value.year
      , value.hourBalance
      , value.vacationBalance
      , value.created
      , value.modified
    )
  }

  def getId : Integer = {
    this.id
  }

  def setId(id : Integer) : Unit = {
    this.id = id
  }

  def getUserId : Integer = {
    this.userId
  }

  def setUserId(userId : Integer) : Unit = {
    this.userId = userId
  }

  def getYear : Integer = {
    this.year
  }

  def setYear(year : Integer) : Unit = {
    this.year = year
  }

  def getHourBalance : BigDecimal = {
    this.hourBalance
  }

  def setHourBalance(hourBalance : BigDecimal) : Unit = {
    this.hourBalance = hourBalance
  }

  def getVacationBalance : BigDecimal = {
    this.vacationBalance
  }

  def setVacationBalance(vacationBalance : BigDecimal) : Unit = {
    this.vacationBalance = vacationBalance
  }

  def getCreated : LocalDateTime = {
    this.created
  }

  def setCreated(created : LocalDateTime) : Unit = {
    this.created = created
  }

  def getModified : LocalDateTime = {
    this.modified
  }

  def setModified(modified : LocalDateTime) : Unit = {
    this.modified = modified
  }

  override def toString : String = {
    val sb = new StringBuilder("TwYearlyBalance (")

    sb.append(id)
    sb.append(", ").append(userId)
    sb.append(", ").append(year)
    sb.append(", ").append(hourBalance)
    sb.append(", ").append(vacationBalance)
    sb.append(", ").append(created)
    sb.append(", ").append(modified)

    sb.append(")");
    return sb.toString
  }
}
