/**
 * This class is generated by jOOQ
 */
package models.jooq.tables


import java.lang.Class
import java.lang.Integer
import java.lang.String
import java.time.LocalDate
import java.time.LocalDateTime
import java.util.Arrays
import java.util.List

import javax.annotation.Generated

import models.jooq.Keys
import models.jooq.WorkentrySchema
import models.jooq.tables.records.ThWorklogRecord

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.UniqueKey
import org.jooq.impl.TableImpl

import scala.Array

import utils.jooq.converters.DateToLocalDateConverter
import utils.jooq.converters.TimestampToLocalDateTimeConverter


object ThWorklog {

  /**
   * The reference instance of <code>workentry_schema.th_worklog</code>
   */
  val TH_WORKLOG = new ThWorklog
}

/**
 * This class is generated by jOOQ.
 */
@Generated(
  value = Array(
    "http://www.jooq.org",
    "jOOQ version:3.8.6"
  ),
  comments = "This class is generated by jOOQ"
)
class ThWorklog(alias : String, aliased : Table[ThWorklogRecord], parameters : Array[ Field[_] ]) extends TableImpl[ThWorklogRecord](alias, WorkentrySchema.WORKENTRY_SCHEMA, aliased, parameters, "") {

  /**
   * The class holding records for this type
   */
  override def getRecordType : Class[ThWorklogRecord] = {
    classOf[ThWorklogRecord]
  }

  /**
   * The column <code>workentry_schema.th_worklog.id</code>.
   */
  val ID : TableField[ThWorklogRecord, Integer] = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('workentry_schema.th_worklog_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), "")

  /**
   * The column <code>workentry_schema.th_worklog.worklog_id</code>.
   */
  val WORKLOG_ID : TableField[ThWorklogRecord, Integer] = createField("worklog_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), "")

  /**
   * The column <code>workentry_schema.th_worklog.user_id</code>.
   */
  val USER_ID : TableField[ThWorklogRecord, Integer] = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), "")

  /**
   * The column <code>workentry_schema.th_worklog.start_date</code>.
   */
  val START_DATE : TableField[ThWorklogRecord, LocalDate] = createField("start_date", org.jooq.impl.SQLDataType.DATE.nullable(false), "", new DateToLocalDateConverter())

  /**
   * The column <code>workentry_schema.th_worklog.end_date</code>.
   */
  val END_DATE : TableField[ThWorklogRecord, LocalDate] = createField("end_date", org.jooq.impl.SQLDataType.DATE, "", new DateToLocalDateConverter())

  /**
   * The column <code>workentry_schema.th_worklog.pause_time</code>.
   */
  val PAUSE_TIME : TableField[ThWorklogRecord, Integer] = createField("pause_time", org.jooq.impl.SQLDataType.INTEGER, "")

  /**
   * The column <code>workentry_schema.th_worklog.notes</code>.
   */
  val NOTES : TableField[ThWorklogRecord, String] = createField("notes", org.jooq.impl.SQLDataType.VARCHAR.length(250), "")

  /**
   * The column <code>workentry_schema.th_worklog.editing_reason</code>.
   */
  val EDITING_REASON : TableField[ThWorklogRecord, String] = createField("editing_reason", org.jooq.impl.SQLDataType.VARCHAR.length(250), "")

  /**
   * The column <code>workentry_schema.th_worklog.update_by</code>.
   */
  val UPDATE_BY : TableField[ThWorklogRecord, Integer] = createField("update_by", org.jooq.impl.SQLDataType.INTEGER.nullable(false), "")

  /**
   * The column <code>workentry_schema.th_worklog.created</code>.
   */
  val CREATED : TableField[ThWorklogRecord, LocalDateTime] = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), "", new TimestampToLocalDateTimeConverter())

  /**
   * The column <code>workentry_schema.th_worklog.modified</code>.
   */
  val MODIFIED : TableField[ThWorklogRecord, LocalDateTime] = createField("modified", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), "", new TimestampToLocalDateTimeConverter())

  /**
   * Create a <code>workentry_schema.th_worklog</code> table reference
   */
  def this() = {
    this("th_worklog", null, null)
  }

  /**
   * Create an aliased <code>workentry_schema.th_worklog</code> table reference
   */
  def this(alias : String) = {
    this(alias, models.jooq.tables.ThWorklog.TH_WORKLOG, null)
  }

  private def this(alias : String, aliased : Table[ThWorklogRecord]) = {
    this(alias, aliased, null)
  }

  override def getSchema : Schema = WorkentrySchema.WORKENTRY_SCHEMA

  override def getIdentity : Identity[ThWorklogRecord, Integer] = {
    Keys.IDENTITY_TH_WORKLOG
  }

  override def getPrimaryKey : UniqueKey[ThWorklogRecord] = {
    Keys.TH_WORKLOG_PKEY
  }

  override def getKeys : List[ UniqueKey[ThWorklogRecord] ] = {
    return Arrays.asList[ UniqueKey[ThWorklogRecord] ](Keys.TH_WORKLOG_PKEY)
  }

  override def getReferences : List[ ForeignKey[ThWorklogRecord, _] ] = {
    return Arrays.asList[ ForeignKey[ThWorklogRecord, _] ](Keys.TH_WORKLOG__TH_WORKLOG_WORKLOG_ID_FKEY, Keys.TH_WORKLOG__TH_WORKLOG_USER_ID_FKEY, Keys.TH_WORKLOG__TH_WORKLOG_UPDATE_BY_FKEY)
  }

  override def as(alias : String) : ThWorklog = {
    new ThWorklog(alias, this)
  }

  /**
   * Rename this table
   */
  def rename(name : String) : ThWorklog = {
    new ThWorklog(name, null)
  }
}
