/**
 * This class is generated by jOOQ
 */
package models.jooq.tables


import java.lang.Class
import java.lang.Integer
import java.lang.String
import java.time.LocalDateTime
import java.util.Arrays
import java.util.List

import javax.annotation.Generated

import models.jooq.Keys
import models.jooq.WorkentrySchema
import models.jooq.tables.records.TmEventTypeRecord

import org.jooq.Field
import org.jooq.Identity
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.UniqueKey
import org.jooq.impl.TableImpl

import scala.Array

import utils.jooq.converters.TimestampToLocalDateTimeConverter


object TmEventType {

  /**
   * The reference instance of <code>workentry_schema.tm_event_type</code>
   */
  val TM_EVENT_TYPE = new TmEventType
}

/**
 * This class is generated by jOOQ.
 */
@Generated(
  value = Array(
    "http://www.jooq.org",
    "jOOQ version:3.8.6"
  ),
  comments = "This class is generated by jOOQ"
)
class TmEventType(alias : String, aliased : Table[TmEventTypeRecord], parameters : Array[ Field[_] ]) extends TableImpl[TmEventTypeRecord](alias, WorkentrySchema.WORKENTRY_SCHEMA, aliased, parameters, "") {

  /**
   * The class holding records for this type
   */
  override def getRecordType : Class[TmEventTypeRecord] = {
    classOf[TmEventTypeRecord]
  }

  /**
   * The column <code>workentry_schema.tm_event_type.id</code>.
   */
  val ID : TableField[TmEventTypeRecord, Integer] = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('workentry_schema.tm_event_type_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), "")

  /**
   * The column <code>workentry_schema.tm_event_type.name</code>.
   */
  val NAME : TableField[TmEventTypeRecord, String] = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), "")

  /**
   * The column <code>workentry_schema.tm_event_type.description</code>.
   */
  val DESCRIPTION : TableField[TmEventTypeRecord, String] = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(250).nullable(false), "")

  /**
   * The column <code>workentry_schema.tm_event_type.color</code>.
   */
  val COLOR : TableField[TmEventTypeRecord, String] = createField("color", org.jooq.impl.SQLDataType.VARCHAR.length(10).nullable(false), "")

  /**
   * The column <code>workentry_schema.tm_event_type.created</code>.
   */
  val CREATED : TableField[TmEventTypeRecord, LocalDateTime] = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), "", new TimestampToLocalDateTimeConverter())

  /**
   * The column <code>workentry_schema.tm_event_type.modified</code>.
   */
  val MODIFIED : TableField[TmEventTypeRecord, LocalDateTime] = createField("modified", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), "", new TimestampToLocalDateTimeConverter())

  /**
   * Create a <code>workentry_schema.tm_event_type</code> table reference
   */
  def this() = {
    this("tm_event_type", null, null)
  }

  /**
   * Create an aliased <code>workentry_schema.tm_event_type</code> table reference
   */
  def this(alias : String) = {
    this(alias, models.jooq.tables.TmEventType.TM_EVENT_TYPE, null)
  }

  private def this(alias : String, aliased : Table[TmEventTypeRecord]) = {
    this(alias, aliased, null)
  }

  override def getSchema : Schema = WorkentrySchema.WORKENTRY_SCHEMA

  override def getIdentity : Identity[TmEventTypeRecord, Integer] = {
    Keys.IDENTITY_TM_EVENT_TYPE
  }

  override def getPrimaryKey : UniqueKey[TmEventTypeRecord] = {
    Keys.TM_EVENT_TYPE_PKEY
  }

  override def getKeys : List[ UniqueKey[TmEventTypeRecord] ] = {
    return Arrays.asList[ UniqueKey[TmEventTypeRecord] ](Keys.TM_EVENT_TYPE_PKEY, Keys.TM_EVENT_TYPE_NAME_KEY)
  }

  override def as(alias : String) : TmEventType = {
    new TmEventType(alias, this)
  }

  /**
   * Rename this table
   */
  def rename(name : String) : TmEventType = {
    new TmEventType(name, null)
  }
}
