/*
 * This file is generated by jOOQ.
*/
package models.jooq.tables


import java.lang.Class
import java.lang.Integer
import java.lang.String
import java.time.LocalDateTime
import java.util.Arrays
import java.util.List

import javax.annotation.Generated

import models.jooq.Keys
import models.jooq.WorkentrySchema
import models.jooq.tables.records.TmRoleRecord

import org.jooq.Field
import org.jooq.Identity
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.UniqueKey
import org.jooq.impl.TableImpl

import scala.Array

import utils.jooq.converters.TimestampToLocalDateTimeConverter


object TmRole {

  /**
   * The reference instance of <code>workentry_schema.tm_role</code>
   */
  val TM_ROLE = new TmRole
}

/**
 * This class is generated by jOOQ.
 */
@Generated(
  value = Array(
    "http://www.jooq.org",
    "jOOQ version:3.9.1"
  ),
  comments = "This class is generated by jOOQ"
)
class TmRole(alias : String, aliased : Table[TmRoleRecord], parameters : Array[ Field[_] ]) extends TableImpl[TmRoleRecord](alias, WorkentrySchema.WORKENTRY_SCHEMA, aliased, parameters, "") {

  /**
   * The class holding records for this type
   */
  override def getRecordType : Class[TmRoleRecord] = {
    classOf[TmRoleRecord]
  }

  /**
   * The column <code>workentry_schema.tm_role.id</code>.
   */
  val ID : TableField[TmRoleRecord, Integer] = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('workentry_schema.tm_role_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), "")

  /**
   * The column <code>workentry_schema.tm_role.name</code>.
   */
  val NAME : TableField[TmRoleRecord, String] = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), "")

  /**
   * The column <code>workentry_schema.tm_role.created</code>.
   */
  val CREATED : TableField[TmRoleRecord, LocalDateTime] = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), "", new TimestampToLocalDateTimeConverter())

  /**
   * The column <code>workentry_schema.tm_role.modified</code>.
   */
  val MODIFIED : TableField[TmRoleRecord, LocalDateTime] = createField("modified", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), "", new TimestampToLocalDateTimeConverter())

  /**
   * Create a <code>workentry_schema.tm_role</code> table reference
   */
  def this() = {
    this("tm_role", null, null)
  }

  /**
   * Create an aliased <code>workentry_schema.tm_role</code> table reference
   */
  def this(alias : String) = {
    this(alias, models.jooq.tables.TmRole.TM_ROLE, null)
  }

  private def this(alias : String, aliased : Table[TmRoleRecord]) = {
    this(alias, aliased, null)
  }

  override def getSchema : Schema = WorkentrySchema.WORKENTRY_SCHEMA

  override def getIdentity : Identity[TmRoleRecord, Integer] = {
    Keys.IDENTITY_TM_ROLE
  }

  override def getPrimaryKey : UniqueKey[TmRoleRecord] = {
    Keys.TM_ROLE_PKEY
  }

  override def getKeys : List[ UniqueKey[TmRoleRecord] ] = {
    return Arrays.asList[ UniqueKey[TmRoleRecord] ](Keys.TM_ROLE_PKEY, Keys.TM_ROLE_NAME_KEY)
  }

  override def as(alias : String) : TmRole = {
    new TmRole(alias, this)
  }

  /**
   * Rename this table
   */
  override def rename(name : String) : TmRole = {
    new TmRole(name, null)
  }
}
