/**
 * This class is generated by jOOQ
 */
package models.jooq.tables


import java.lang.Class
import java.lang.Integer
import java.lang.String
import java.time.LocalDateTime
import java.util.Arrays
import java.util.List

import javax.annotation.Generated

import models.jooq.Keys
import models.jooq.WorkentrySchema
import models.jooq.tables.records.TmUserRecord

import org.jooq.Field
import org.jooq.Identity
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.UniqueKey
import org.jooq.impl.TableImpl

import scala.Array

import utils.jooq.converters.TimestampToLocalDateTimeConverter


object TmUser {

  /**
   * The reference instance of <code>workentry_schema.tm_user</code>
   */
  val TM_USER = new TmUser
}

/**
 * This class is generated by jOOQ.
 */
@Generated(
  value = Array(
    "http://www.jooq.org",
    "jOOQ version:3.8.6"
  ),
  comments = "This class is generated by jOOQ"
)
class TmUser(alias : String, aliased : Table[TmUserRecord], parameters : Array[ Field[_] ]) extends TableImpl[TmUserRecord](alias, WorkentrySchema.WORKENTRY_SCHEMA, aliased, parameters, "") {

  /**
   * The class holding records for this type
   */
  override def getRecordType : Class[TmUserRecord] = {
    classOf[TmUserRecord]
  }

  /**
   * The column <code>workentry_schema.tm_user.id</code>.
   */
  val ID : TableField[TmUserRecord, Integer] = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('workentry_schema.tm_user_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), "")

  /**
   * The column <code>workentry_schema.tm_user.name</code>.
   */
  val NAME : TableField[TmUserRecord, String] = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), "")

  /**
   * The column <code>workentry_schema.tm_user.email</code>.
   */
  val EMAIL : TableField[TmUserRecord, String] = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(50), "")

  /**
   * The column <code>workentry_schema.tm_user.nif</code>.
   */
  val NIF : TableField[TmUserRecord, String] = createField("nif", org.jooq.impl.SQLDataType.VARCHAR.length(15).nullable(false), "")

  /**
   * The column <code>workentry_schema.tm_user.afiliation_no</code>.
   */
  val AFILIATION_NO : TableField[TmUserRecord, String] = createField("afiliation_no", org.jooq.impl.SQLDataType.VARCHAR.length(15).nullable(false), "")

  /**
   * The column <code>workentry_schema.tm_user.login_name</code>.
   */
  val LOGIN_NAME : TableField[TmUserRecord, String] = createField("login_name", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), "")

  /**
   * The column <code>workentry_schema.tm_user.password</code>.
   */
  val PASSWORD : TableField[TmUserRecord, String] = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), "")

  /**
   * The column <code>workentry_schema.tm_user.created</code>.
   */
  val CREATED : TableField[TmUserRecord, LocalDateTime] = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), "", new TimestampToLocalDateTimeConverter())

  /**
   * The column <code>workentry_schema.tm_user.modified</code>.
   */
  val MODIFIED : TableField[TmUserRecord, LocalDateTime] = createField("modified", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), "", new TimestampToLocalDateTimeConverter())

  /**
   * Create a <code>workentry_schema.tm_user</code> table reference
   */
  def this() = {
    this("tm_user", null, null)
  }

  /**
   * Create an aliased <code>workentry_schema.tm_user</code> table reference
   */
  def this(alias : String) = {
    this(alias, models.jooq.tables.TmUser.TM_USER, null)
  }

  private def this(alias : String, aliased : Table[TmUserRecord]) = {
    this(alias, aliased, null)
  }

  override def getSchema : Schema = WorkentrySchema.WORKENTRY_SCHEMA

  override def getIdentity : Identity[TmUserRecord, Integer] = {
    Keys.IDENTITY_TM_USER
  }

  override def getPrimaryKey : UniqueKey[TmUserRecord] = {
    Keys.TM_USER_PKEY
  }

  override def getKeys : List[ UniqueKey[TmUserRecord] ] = {
    return Arrays.asList[ UniqueKey[TmUserRecord] ](Keys.TM_USER_PKEY, Keys.TM_USER_NIF_KEY, Keys.TM_USER_AFILIATION_NO_KEY, Keys.TM_USER_LOGIN_NAME_KEY)
  }

  override def as(alias : String) : TmUser = {
    new TmUser(alias, this)
  }

  /**
   * Rename this table
   */
  def rename(name : String) : TmUser = {
    new TmUser(name, null)
  }
}
