/**
 * This class is generated by jOOQ
 */
package models.jooq.tables


import java.lang.Class
import java.lang.Integer
import java.lang.String
import java.time.LocalDate
import java.time.LocalDateTime
import java.util.Arrays
import java.util.List

import javax.annotation.Generated

import models.jooq.Keys
import models.jooq.WorkentrySchema
import models.jooq.tables.records.TmUserContractRecord

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.UniqueKey
import org.jooq.impl.TableImpl

import scala.Array

import utils.jooq.converters.DateToLocalDateConverter
import utils.jooq.converters.TimestampToLocalDateTimeConverter


object TmUserContract {

  /**
   * The reference instance of <code>workentry_schema.tm_user_contract</code>
   */
  val TM_USER_CONTRACT = new TmUserContract
}

/**
 * This class is generated by jOOQ.
 */
@Generated(
  value = Array(
    "http://www.jooq.org",
    "jOOQ version:3.8.6"
  ),
  comments = "This class is generated by jOOQ"
)
class TmUserContract(alias : String, aliased : Table[TmUserContractRecord], parameters : Array[ Field[_] ]) extends TableImpl[TmUserContractRecord](alias, WorkentrySchema.WORKENTRY_SCHEMA, aliased, parameters, "") {

  /**
   * The class holding records for this type
   */
  override def getRecordType : Class[TmUserContractRecord] = {
    classOf[TmUserContractRecord]
  }

  /**
   * The column <code>workentry_schema.tm_user_contract.id</code>.
   */
  val ID : TableField[TmUserContractRecord, Integer] = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('workentry_schema.tm_user_contract_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), "")

  /**
   * The column <code>workentry_schema.tm_user_contract.user_id</code>.
   */
  val USER_ID : TableField[TmUserContractRecord, Integer] = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), "")

  /**
   * The column <code>workentry_schema.tm_user_contract.description</code>.
   */
  val DESCRIPTION : TableField[TmUserContractRecord, String] = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(250).nullable(false), "")

  /**
   * The column <code>workentry_schema.tm_user_contract.hours_per_week</code>.
   */
  val HOURS_PER_WEEK : TableField[TmUserContractRecord, Integer] = createField("hours_per_week", org.jooq.impl.SQLDataType.INTEGER.nullable(false), "")

  /**
   * The column <code>workentry_schema.tm_user_contract.days_per_week</code>.
   */
  val DAYS_PER_WEEK : TableField[TmUserContractRecord, Integer] = createField("days_per_week", org.jooq.impl.SQLDataType.INTEGER.nullable(false), "")

  /**
   * The column <code>workentry_schema.tm_user_contract.start_date</code>.
   */
  val START_DATE : TableField[TmUserContractRecord, LocalDate] = createField("start_date", org.jooq.impl.SQLDataType.DATE.nullable(false), "", new DateToLocalDateConverter())

  /**
   * The column <code>workentry_schema.tm_user_contract.end_date</code>.
   */
  val END_DATE : TableField[TmUserContractRecord, LocalDate] = createField("end_date", org.jooq.impl.SQLDataType.DATE.nullable(false), "", new DateToLocalDateConverter())

  /**
   * The column <code>workentry_schema.tm_user_contract.created</code>.
   */
  val CREATED : TableField[TmUserContractRecord, LocalDateTime] = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), "", new TimestampToLocalDateTimeConverter())

  /**
   * The column <code>workentry_schema.tm_user_contract.modified</code>.
   */
  val MODIFIED : TableField[TmUserContractRecord, LocalDateTime] = createField("modified", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), "", new TimestampToLocalDateTimeConverter())

  /**
   * Create a <code>workentry_schema.tm_user_contract</code> table reference
   */
  def this() = {
    this("tm_user_contract", null, null)
  }

  /**
   * Create an aliased <code>workentry_schema.tm_user_contract</code> table reference
   */
  def this(alias : String) = {
    this(alias, models.jooq.tables.TmUserContract.TM_USER_CONTRACT, null)
  }

  private def this(alias : String, aliased : Table[TmUserContractRecord]) = {
    this(alias, aliased, null)
  }

  override def getSchema : Schema = WorkentrySchema.WORKENTRY_SCHEMA

  override def getIdentity : Identity[TmUserContractRecord, Integer] = {
    Keys.IDENTITY_TM_USER_CONTRACT
  }

  override def getPrimaryKey : UniqueKey[TmUserContractRecord] = {
    Keys.TM_USER_CONTRACT_PKEY
  }

  override def getKeys : List[ UniqueKey[TmUserContractRecord] ] = {
    return Arrays.asList[ UniqueKey[TmUserContractRecord] ](Keys.TM_USER_CONTRACT_PKEY)
  }

  override def getReferences : List[ ForeignKey[TmUserContractRecord, _] ] = {
    return Arrays.asList[ ForeignKey[TmUserContractRecord, _] ](Keys.TM_USER_CONTRACT__TM_USER_CONTRACT_USER_ID_FKEY)
  }

  override def as(alias : String) : TmUserContract = {
    new TmUserContract(alias, this)
  }

  /**
   * Rename this table
   */
  def rename(name : String) : TmUserContract = {
    new TmUserContract(name, null)
  }
}
