/*
 * This file is generated by jOOQ.
*/
package models.jooq.tables


import java.lang.Boolean
import java.lang.Class
import java.lang.Integer
import java.lang.String
import java.time.LocalDate
import java.time.LocalDateTime
import java.util.Arrays
import java.util.List

import javax.annotation.Generated

import models.jooq.Keys
import models.jooq.WorkentrySchema
import models.jooq.tables.records.TwEventRecord

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.UniqueKey
import org.jooq.impl.TableImpl

import scala.Array

import utils.jooq.converters.DateToLocalDateConverter
import utils.jooq.converters.TimestampToLocalDateTimeConverter


object TwEvent {

  /**
   * The reference instance of <code>workentry_schema.tw_event</code>
   */
  val TW_EVENT = new TwEvent
}

/**
 * This class is generated by jOOQ.
 */
@Generated(
  value = Array(
    "http://www.jooq.org",
    "jOOQ version:3.9.1"
  ),
  comments = "This class is generated by jOOQ"
)
class TwEvent(alias : String, aliased : Table[TwEventRecord], parameters : Array[ Field[_] ]) extends TableImpl[TwEventRecord](alias, WorkentrySchema.WORKENTRY_SCHEMA, aliased, parameters, "") {

  /**
   * The class holding records for this type
   */
  override def getRecordType : Class[TwEventRecord] = {
    classOf[TwEventRecord]
  }

  /**
   * The column <code>workentry_schema.tw_event.id</code>.
   */
  val ID : TableField[TwEventRecord, Integer] = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('workentry_schema.tw_event_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), "")

  /**
   * The column <code>workentry_schema.tw_event.user_id</code>.
   */
  val USER_ID : TableField[TwEventRecord, Integer] = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), "")

  /**
   * The column <code>workentry_schema.tw_event.start_date</code>.
   */
  val START_DATE : TableField[TwEventRecord, LocalDate] = createField("start_date", org.jooq.impl.SQLDataType.DATE.nullable(false), "", new DateToLocalDateConverter())

  /**
   * The column <code>workentry_schema.tw_event.end_date</code>.
   */
  val END_DATE : TableField[TwEventRecord, LocalDate] = createField("end_date", org.jooq.impl.SQLDataType.DATE, "", new DateToLocalDateConverter())

  /**
   * The column <code>workentry_schema.tw_event.all_day_event</code>.
   */
  val ALL_DAY_EVENT : TableField[TwEventRecord, Boolean] = createField("all_day_event", org.jooq.impl.SQLDataType.BOOLEAN, "")

  /**
   * The column <code>workentry_schema.tw_event.type</code>.
   */
  val TYPE : TableField[TwEventRecord, Integer] = createField("type", org.jooq.impl.SQLDataType.INTEGER.nullable(false), "")

  /**
   * The column <code>workentry_schema.tw_event.description</code>.
   */
  val DESCRIPTION : TableField[TwEventRecord, String] = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(255), "")

  /**
   * The column <code>workentry_schema.tw_event.created</code>.
   */
  val CREATED : TableField[TwEventRecord, LocalDateTime] = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), "", new TimestampToLocalDateTimeConverter())

  /**
   * The column <code>workentry_schema.tw_event.modified</code>.
   */
  val MODIFIED : TableField[TwEventRecord, LocalDateTime] = createField("modified", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), "", new TimestampToLocalDateTimeConverter())

  /**
   * Create a <code>workentry_schema.tw_event</code> table reference
   */
  def this() = {
    this("tw_event", null, null)
  }

  /**
   * Create an aliased <code>workentry_schema.tw_event</code> table reference
   */
  def this(alias : String) = {
    this(alias, models.jooq.tables.TwEvent.TW_EVENT, null)
  }

  private def this(alias : String, aliased : Table[TwEventRecord]) = {
    this(alias, aliased, null)
  }

  override def getSchema : Schema = WorkentrySchema.WORKENTRY_SCHEMA

  override def getIdentity : Identity[TwEventRecord, Integer] = {
    Keys.IDENTITY_TW_EVENT
  }

  override def getPrimaryKey : UniqueKey[TwEventRecord] = {
    Keys.TW_EVENT_PKEY
  }

  override def getKeys : List[ UniqueKey[TwEventRecord] ] = {
    return Arrays.asList[ UniqueKey[TwEventRecord] ](Keys.TW_EVENT_PKEY)
  }

  override def getReferences : List[ ForeignKey[TwEventRecord, _] ] = {
    return Arrays.asList[ ForeignKey[TwEventRecord, _] ](Keys.TW_EVENT__TW_EVENT_USER_ID_FKEY, Keys.TW_EVENT__TW_EVENT_TYPE_FKEY)
  }

  override def as(alias : String) : TwEvent = {
    new TwEvent(alias, this)
  }

  /**
   * Rename this table
   */
  override def rename(name : String) : TwEvent = {
    new TwEvent(name, null)
  }
}
