/**
 * This class is generated by jOOQ
 */
package models.jooq.tables


import java.lang.Class
import java.lang.Integer
import java.lang.String
import java.math.BigDecimal
import java.time.LocalDateTime
import java.util.Arrays
import java.util.List

import javax.annotation.Generated

import models.jooq.Keys
import models.jooq.WorkentrySchema
import models.jooq.tables.records.TwYearlyBalanceRecord

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.UniqueKey
import org.jooq.impl.TableImpl

import scala.Array

import utils.jooq.converters.TimestampToLocalDateTimeConverter


object TwYearlyBalance {

  /**
   * The reference instance of <code>workentry_schema.tw_yearly_balance</code>
   */
  val TW_YEARLY_BALANCE = new TwYearlyBalance
}

/**
 * This class is generated by jOOQ.
 */
@Generated(
  value = Array(
    "http://www.jooq.org",
    "jOOQ version:3.8.6"
  ),
  comments = "This class is generated by jOOQ"
)
class TwYearlyBalance(alias : String, aliased : Table[TwYearlyBalanceRecord], parameters : Array[ Field[_] ]) extends TableImpl[TwYearlyBalanceRecord](alias, WorkentrySchema.WORKENTRY_SCHEMA, aliased, parameters, "") {

  /**
   * The class holding records for this type
   */
  override def getRecordType : Class[TwYearlyBalanceRecord] = {
    classOf[TwYearlyBalanceRecord]
  }

  /**
   * The column <code>workentry_schema.tw_yearly_balance.id</code>.
   */
  val ID : TableField[TwYearlyBalanceRecord, Integer] = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('workentry_schema.tw_yearly_balance_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), "")

  /**
   * The column <code>workentry_schema.tw_yearly_balance.user_id</code>.
   */
  val USER_ID : TableField[TwYearlyBalanceRecord, Integer] = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), "")

  /**
   * The column <code>workentry_schema.tw_yearly_balance.year</code>.
   */
  val YEAR : TableField[TwYearlyBalanceRecord, Integer] = createField("year", org.jooq.impl.SQLDataType.INTEGER.nullable(false), "")

  /**
   * The column <code>workentry_schema.tw_yearly_balance.hour_balance</code>.
   */
  val HOUR_BALANCE : TableField[TwYearlyBalanceRecord, BigDecimal] = createField("hour_balance", org.jooq.impl.SQLDataType.NUMERIC.nullable(false), "")

  /**
   * The column <code>workentry_schema.tw_yearly_balance.vacation_balance</code>.
   */
  val VACATION_BALANCE : TableField[TwYearlyBalanceRecord, BigDecimal] = createField("vacation_balance", org.jooq.impl.SQLDataType.NUMERIC, "")

  /**
   * The column <code>workentry_schema.tw_yearly_balance.created</code>.
   */
  val CREATED : TableField[TwYearlyBalanceRecord, LocalDateTime] = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), "", new TimestampToLocalDateTimeConverter())

  /**
   * The column <code>workentry_schema.tw_yearly_balance.modified</code>.
   */
  val MODIFIED : TableField[TwYearlyBalanceRecord, LocalDateTime] = createField("modified", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), "", new TimestampToLocalDateTimeConverter())

  /**
   * Create a <code>workentry_schema.tw_yearly_balance</code> table reference
   */
  def this() = {
    this("tw_yearly_balance", null, null)
  }

  /**
   * Create an aliased <code>workentry_schema.tw_yearly_balance</code> table reference
   */
  def this(alias : String) = {
    this(alias, models.jooq.tables.TwYearlyBalance.TW_YEARLY_BALANCE, null)
  }

  private def this(alias : String, aliased : Table[TwYearlyBalanceRecord]) = {
    this(alias, aliased, null)
  }

  override def getSchema : Schema = WorkentrySchema.WORKENTRY_SCHEMA

  override def getIdentity : Identity[TwYearlyBalanceRecord, Integer] = {
    Keys.IDENTITY_TW_YEARLY_BALANCE
  }

  override def getPrimaryKey : UniqueKey[TwYearlyBalanceRecord] = {
    Keys.TW_YEARLY_BALANCE_PKEY
  }

  override def getKeys : List[ UniqueKey[TwYearlyBalanceRecord] ] = {
    return Arrays.asList[ UniqueKey[TwYearlyBalanceRecord] ](Keys.TW_YEARLY_BALANCE_PKEY)
  }

  override def getReferences : List[ ForeignKey[TwYearlyBalanceRecord, _] ] = {
    return Arrays.asList[ ForeignKey[TwYearlyBalanceRecord, _] ](Keys.TW_YEARLY_BALANCE__TW_YEARLY_BALANCE_USER_ID_FKEY)
  }

  override def as(alias : String) : TwYearlyBalance = {
    new TwYearlyBalance(alias, this)
  }

  /**
   * Rename this table
   */
  def rename(name : String) : TwYearlyBalance = {
    new TwYearlyBalance(name, null)
  }
}
