/*
 * This file is generated by jOOQ.
*/
package models.jooq.routines


import java.lang.Object

import javax.annotation.Generated

import models.jooq.WorkentrySchema

import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine

import scala.Array


object UpdateModifiedColumn {

  /**
   * The parameter <code>workentry_schema.update_modified_column.RETURN_VALUE</code>.
   */
  val RETURN_VALUE : Parameter[Object] = AbstractRoutine.createParameter("RETURN_VALUE", org.jooq.impl.DefaultDataType.getDefaultDataType("trigger"), false, false)
}

/**
 * This class is generated by jOOQ.
 */
@Generated(
  value = Array(
    "http://www.jooq.org",
    "jOOQ version:3.9.1"
  ),
  comments = "This class is generated by jOOQ"
)
class UpdateModifiedColumn extends AbstractRoutine[Object]("update_modified_column", WorkentrySchema.WORKENTRY_SCHEMA, org.jooq.impl.DefaultDataType.getDefaultDataType("trigger")) {
  {
    setReturnParameter(UpdateModifiedColumn.RETURN_VALUE)
  }
}
