/**
 * This class is generated by jOOQ
 */
package models.jooq.tables.records


import java.lang.Integer
import java.lang.String
import java.time.LocalDateTime

import javax.annotation.Generated

import models.jooq.tables.TmEventType

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record6
import org.jooq.Row6
import org.jooq.impl.UpdatableRecordImpl

import scala.Array


/**
 * This class is generated by jOOQ.
 */
@Generated(
  value = Array(
    "http://www.jooq.org",
    "jOOQ version:3.8.6"
  ),
  comments = "This class is generated by jOOQ"
)
class TmEventTypeRecord extends UpdatableRecordImpl[TmEventTypeRecord](TmEventType.TM_EVENT_TYPE) with Record6[Integer, String, String, String, LocalDateTime, LocalDateTime] {

  /**
   * Setter for <code>workentry_schema.tm_event_type.id</code>.
   */
  def setId(value : Integer) : Unit = {
    set(0, value)
  }

  /**
   * Getter for <code>workentry_schema.tm_event_type.id</code>.
   */
  def getId : Integer = {
    val r = get(0)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  /**
   * Setter for <code>workentry_schema.tm_event_type.name</code>.
   */
  def setName(value : String) : Unit = {
    set(1, value)
  }

  /**
   * Getter for <code>workentry_schema.tm_event_type.name</code>.
   */
  def getName : String = {
    val r = get(1)
    if (r == null) null else r.asInstanceOf[String]
  }

  /**
   * Setter for <code>workentry_schema.tm_event_type.description</code>.
   */
  def setDescription(value : String) : Unit = {
    set(2, value)
  }

  /**
   * Getter for <code>workentry_schema.tm_event_type.description</code>.
   */
  def getDescription : String = {
    val r = get(2)
    if (r == null) null else r.asInstanceOf[String]
  }

  /**
   * Setter for <code>workentry_schema.tm_event_type.color</code>.
   */
  def setColor(value : String) : Unit = {
    set(3, value)
  }

  /**
   * Getter for <code>workentry_schema.tm_event_type.color</code>.
   */
  def getColor : String = {
    val r = get(3)
    if (r == null) null else r.asInstanceOf[String]
  }

  /**
   * Setter for <code>workentry_schema.tm_event_type.created</code>.
   */
  def setCreated(value : LocalDateTime) : Unit = {
    set(4, value)
  }

  /**
   * Getter for <code>workentry_schema.tm_event_type.created</code>.
   */
  def getCreated : LocalDateTime = {
    val r = get(4)
    if (r == null) null else r.asInstanceOf[LocalDateTime]
  }

  /**
   * Setter for <code>workentry_schema.tm_event_type.modified</code>.
   */
  def setModified(value : LocalDateTime) : Unit = {
    set(5, value)
  }

  /**
   * Getter for <code>workentry_schema.tm_event_type.modified</code>.
   */
  def getModified : LocalDateTime = {
    val r = get(5)
    if (r == null) null else r.asInstanceOf[LocalDateTime]
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------
  override def key() : Record1[Integer] = {
    return super.key.asInstanceOf[ Record1[Integer] ]
  }

  // -------------------------------------------------------------------------
  // Record6 type implementation
  // -------------------------------------------------------------------------

  override def fieldsRow : Row6[Integer, String, String, String, LocalDateTime, LocalDateTime] = {
    super.fieldsRow.asInstanceOf[ Row6[Integer, String, String, String, LocalDateTime, LocalDateTime] ]
  }

  override def valuesRow : Row6[Integer, String, String, String, LocalDateTime, LocalDateTime] = {
    super.valuesRow.asInstanceOf[ Row6[Integer, String, String, String, LocalDateTime, LocalDateTime] ]
  }
  override def field1 : Field[Integer] = TmEventType.TM_EVENT_TYPE.ID
  override def field2 : Field[String] = TmEventType.TM_EVENT_TYPE.NAME
  override def field3 : Field[String] = TmEventType.TM_EVENT_TYPE.DESCRIPTION
  override def field4 : Field[String] = TmEventType.TM_EVENT_TYPE.COLOR
  override def field5 : Field[LocalDateTime] = TmEventType.TM_EVENT_TYPE.CREATED
  override def field6 : Field[LocalDateTime] = TmEventType.TM_EVENT_TYPE.MODIFIED
  override def value1 : Integer = getId
  override def value2 : String = getName
  override def value3 : String = getDescription
  override def value4 : String = getColor
  override def value5 : LocalDateTime = getCreated
  override def value6 : LocalDateTime = getModified

  override def value1(value : Integer) : TmEventTypeRecord = {
    setId(value)
    this
  }

  override def value2(value : String) : TmEventTypeRecord = {
    setName(value)
    this
  }

  override def value3(value : String) : TmEventTypeRecord = {
    setDescription(value)
    this
  }

  override def value4(value : String) : TmEventTypeRecord = {
    setColor(value)
    this
  }

  override def value5(value : LocalDateTime) : TmEventTypeRecord = {
    setCreated(value)
    this
  }

  override def value6(value : LocalDateTime) : TmEventTypeRecord = {
    setModified(value)
    this
  }

  override def values(value1 : Integer, value2 : String, value3 : String, value4 : String, value5 : LocalDateTime, value6 : LocalDateTime) : TmEventTypeRecord = {
    this.value1(value1)
    this.value2(value2)
    this.value3(value3)
    this.value4(value4)
    this.value5(value5)
    this.value6(value6)
    this
  }

  /**
   * Create a detached, initialised TmEventTypeRecord
   */
  def this(id : Integer, name : String, description : String, color : String, created : LocalDateTime, modified : LocalDateTime) = {
    this()

    set(0, id)
    set(1, name)
    set(2, description)
    set(3, color)
    set(4, created)
    set(5, modified)
  }
}
