/**
 * This class is generated by jOOQ
 */
package models.jooq.tables.records


import java.lang.Integer
import java.lang.String
import java.time.LocalDateTime

import javax.annotation.Generated

import models.jooq.tables.TmRole

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record4
import org.jooq.Row4
import org.jooq.impl.UpdatableRecordImpl

import scala.Array


/**
 * This class is generated by jOOQ.
 */
@Generated(
  value = Array(
    "http://www.jooq.org",
    "jOOQ version:3.8.6"
  ),
  comments = "This class is generated by jOOQ"
)
class TmRoleRecord extends UpdatableRecordImpl[TmRoleRecord](TmRole.TM_ROLE) with Record4[Integer, String, LocalDateTime, LocalDateTime] {

  /**
   * Setter for <code>workentry_schema.tm_role.id</code>.
   */
  def setId(value : Integer) : Unit = {
    set(0, value)
  }

  /**
   * Getter for <code>workentry_schema.tm_role.id</code>.
   */
  def getId : Integer = {
    val r = get(0)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  /**
   * Setter for <code>workentry_schema.tm_role.name</code>.
   */
  def setName(value : String) : Unit = {
    set(1, value)
  }

  /**
   * Getter for <code>workentry_schema.tm_role.name</code>.
   */
  def getName : String = {
    val r = get(1)
    if (r == null) null else r.asInstanceOf[String]
  }

  /**
   * Setter for <code>workentry_schema.tm_role.created</code>.
   */
  def setCreated(value : LocalDateTime) : Unit = {
    set(2, value)
  }

  /**
   * Getter for <code>workentry_schema.tm_role.created</code>.
   */
  def getCreated : LocalDateTime = {
    val r = get(2)
    if (r == null) null else r.asInstanceOf[LocalDateTime]
  }

  /**
   * Setter for <code>workentry_schema.tm_role.modified</code>.
   */
  def setModified(value : LocalDateTime) : Unit = {
    set(3, value)
  }

  /**
   * Getter for <code>workentry_schema.tm_role.modified</code>.
   */
  def getModified : LocalDateTime = {
    val r = get(3)
    if (r == null) null else r.asInstanceOf[LocalDateTime]
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------
  override def key() : Record1[Integer] = {
    return super.key.asInstanceOf[ Record1[Integer] ]
  }

  // -------------------------------------------------------------------------
  // Record4 type implementation
  // -------------------------------------------------------------------------

  override def fieldsRow : Row4[Integer, String, LocalDateTime, LocalDateTime] = {
    super.fieldsRow.asInstanceOf[ Row4[Integer, String, LocalDateTime, LocalDateTime] ]
  }

  override def valuesRow : Row4[Integer, String, LocalDateTime, LocalDateTime] = {
    super.valuesRow.asInstanceOf[ Row4[Integer, String, LocalDateTime, LocalDateTime] ]
  }
  override def field1 : Field[Integer] = TmRole.TM_ROLE.ID
  override def field2 : Field[String] = TmRole.TM_ROLE.NAME
  override def field3 : Field[LocalDateTime] = TmRole.TM_ROLE.CREATED
  override def field4 : Field[LocalDateTime] = TmRole.TM_ROLE.MODIFIED
  override def value1 : Integer = getId
  override def value2 : String = getName
  override def value3 : LocalDateTime = getCreated
  override def value4 : LocalDateTime = getModified

  override def value1(value : Integer) : TmRoleRecord = {
    setId(value)
    this
  }

  override def value2(value : String) : TmRoleRecord = {
    setName(value)
    this
  }

  override def value3(value : LocalDateTime) : TmRoleRecord = {
    setCreated(value)
    this
  }

  override def value4(value : LocalDateTime) : TmRoleRecord = {
    setModified(value)
    this
  }

  override def values(value1 : Integer, value2 : String, value3 : LocalDateTime, value4 : LocalDateTime) : TmRoleRecord = {
    this.value1(value1)
    this.value2(value2)
    this.value3(value3)
    this.value4(value4)
    this
  }

  /**
   * Create a detached, initialised TmRoleRecord
   */
  def this(id : Integer, name : String, created : LocalDateTime, modified : LocalDateTime) = {
    this()

    set(0, id)
    set(1, name)
    set(2, created)
    set(3, modified)
  }
}
