/*
 * This file is generated by jOOQ.
*/
package models.jooq.tables.records


import java.lang.Integer
import java.lang.String
import java.time.LocalDateTime

import javax.annotation.Generated

import models.jooq.tables.TwNews

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record6
import org.jooq.Row6
import org.jooq.impl.UpdatableRecordImpl

import scala.Array


/**
 * This class is generated by jOOQ.
 */
@Generated(
  value = Array(
    "http://www.jooq.org",
    "jOOQ version:3.9.1"
  ),
  comments = "This class is generated by jOOQ"
)
class TwNewsRecord extends UpdatableRecordImpl[TwNewsRecord](TwNews.TW_NEWS) with Record6[Integer, String, String, Integer, LocalDateTime, LocalDateTime] {

  /**
   * Setter for <code>workentry_schema.tw_news.id</code>.
   */
  def setId(value : Integer) : Unit = {
    set(0, value)
  }

  /**
   * Getter for <code>workentry_schema.tw_news.id</code>.
   */
  def getId : Integer = {
    val r = get(0)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  /**
   * Setter for <code>workentry_schema.tw_news.title</code>.
   */
  def setTitle(value : String) : Unit = {
    set(1, value)
  }

  /**
   * Getter for <code>workentry_schema.tw_news.title</code>.
   */
  def getTitle : String = {
    val r = get(1)
    if (r == null) null else r.asInstanceOf[String]
  }

  /**
   * Setter for <code>workentry_schema.tw_news.body</code>.
   */
  def setBody(value : String) : Unit = {
    set(2, value)
  }

  /**
   * Getter for <code>workentry_schema.tw_news.body</code>.
   */
  def getBody : String = {
    val r = get(2)
    if (r == null) null else r.asInstanceOf[String]
  }

  /**
   * Setter for <code>workentry_schema.tw_news.author_id</code>.
   */
  def setAuthorId(value : Integer) : Unit = {
    set(3, value)
  }

  /**
   * Getter for <code>workentry_schema.tw_news.author_id</code>.
   */
  def getAuthorId : Integer = {
    val r = get(3)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  /**
   * Setter for <code>workentry_schema.tw_news.created</code>.
   */
  def setCreated(value : LocalDateTime) : Unit = {
    set(4, value)
  }

  /**
   * Getter for <code>workentry_schema.tw_news.created</code>.
   */
  def getCreated : LocalDateTime = {
    val r = get(4)
    if (r == null) null else r.asInstanceOf[LocalDateTime]
  }

  /**
   * Setter for <code>workentry_schema.tw_news.modified</code>.
   */
  def setModified(value : LocalDateTime) : Unit = {
    set(5, value)
  }

  /**
   * Getter for <code>workentry_schema.tw_news.modified</code>.
   */
  def getModified : LocalDateTime = {
    val r = get(5)
    if (r == null) null else r.asInstanceOf[LocalDateTime]
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------
  override def key : Record1[Integer] = {
    return super.key.asInstanceOf[ Record1[Integer] ]
  }

  // -------------------------------------------------------------------------
  // Record6 type implementation
  // -------------------------------------------------------------------------

  override def fieldsRow : Row6[Integer, String, String, Integer, LocalDateTime, LocalDateTime] = {
    super.fieldsRow.asInstanceOf[ Row6[Integer, String, String, Integer, LocalDateTime, LocalDateTime] ]
  }

  override def valuesRow : Row6[Integer, String, String, Integer, LocalDateTime, LocalDateTime] = {
    super.valuesRow.asInstanceOf[ Row6[Integer, String, String, Integer, LocalDateTime, LocalDateTime] ]
  }
  override def field1 : Field[Integer] = TwNews.TW_NEWS.ID
  override def field2 : Field[String] = TwNews.TW_NEWS.TITLE
  override def field3 : Field[String] = TwNews.TW_NEWS.BODY
  override def field4 : Field[Integer] = TwNews.TW_NEWS.AUTHOR_ID
  override def field5 : Field[LocalDateTime] = TwNews.TW_NEWS.CREATED
  override def field6 : Field[LocalDateTime] = TwNews.TW_NEWS.MODIFIED
  override def value1 : Integer = getId
  override def value2 : String = getTitle
  override def value3 : String = getBody
  override def value4 : Integer = getAuthorId
  override def value5 : LocalDateTime = getCreated
  override def value6 : LocalDateTime = getModified

  override def value1(value : Integer) : TwNewsRecord = {
    setId(value)
    this
  }

  override def value2(value : String) : TwNewsRecord = {
    setTitle(value)
    this
  }

  override def value3(value : String) : TwNewsRecord = {
    setBody(value)
    this
  }

  override def value4(value : Integer) : TwNewsRecord = {
    setAuthorId(value)
    this
  }

  override def value5(value : LocalDateTime) : TwNewsRecord = {
    setCreated(value)
    this
  }

  override def value6(value : LocalDateTime) : TwNewsRecord = {
    setModified(value)
    this
  }

  override def values(value1 : Integer, value2 : String, value3 : String, value4 : Integer, value5 : LocalDateTime, value6 : LocalDateTime) : TwNewsRecord = {
    this.value1(value1)
    this.value2(value2)
    this.value3(value3)
    this.value4(value4)
    this.value5(value5)
    this.value6(value6)
    this
  }

  /**
   * Create a detached, initialised TwNewsRecord
   */
  def this(id : Integer, title : String, body : String, authorId : Integer, created : LocalDateTime, modified : LocalDateTime) = {
    this()

    set(0, id)
    set(1, title)
    set(2, body)
    set(3, authorId)
    set(4, created)
    set(5, modified)
  }
}
