/*
 * This file is generated by jOOQ.
*/
package models.jooq.tables.records


import java.lang.Integer
import java.lang.String
import java.time.LocalDate
import java.time.LocalDateTime

import javax.annotation.Generated

import models.jooq.tables.TwWorklog

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record10
import org.jooq.Row10
import org.jooq.impl.UpdatableRecordImpl

import scala.Array


/**
 * This class is generated by jOOQ.
 */
@Generated(
  value = Array(
    "http://www.jooq.org",
    "jOOQ version:3.9.1"
  ),
  comments = "This class is generated by jOOQ"
)
class TwWorklogRecord extends UpdatableRecordImpl[TwWorklogRecord](TwWorklog.TW_WORKLOG) with Record10[Integer, Integer, LocalDate, LocalDate, Integer, String, String, Integer, LocalDateTime, LocalDateTime] {

  /**
   * Setter for <code>workentry_schema.tw_worklog.id</code>.
   */
  def setId(value : Integer) : Unit = {
    set(0, value)
  }

  /**
   * Getter for <code>workentry_schema.tw_worklog.id</code>.
   */
  def getId : Integer = {
    val r = get(0)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  /**
   * Setter for <code>workentry_schema.tw_worklog.user_id</code>.
   */
  def setUserId(value : Integer) : Unit = {
    set(1, value)
  }

  /**
   * Getter for <code>workentry_schema.tw_worklog.user_id</code>.
   */
  def getUserId : Integer = {
    val r = get(1)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  /**
   * Setter for <code>workentry_schema.tw_worklog.start_date</code>.
   */
  def setStartDate(value : LocalDate) : Unit = {
    set(2, value)
  }

  /**
   * Getter for <code>workentry_schema.tw_worklog.start_date</code>.
   */
  def getStartDate : LocalDate = {
    val r = get(2)
    if (r == null) null else r.asInstanceOf[LocalDate]
  }

  /**
   * Setter for <code>workentry_schema.tw_worklog.end_date</code>.
   */
  def setEndDate(value : LocalDate) : Unit = {
    set(3, value)
  }

  /**
   * Getter for <code>workentry_schema.tw_worklog.end_date</code>.
   */
  def getEndDate : LocalDate = {
    val r = get(3)
    if (r == null) null else r.asInstanceOf[LocalDate]
  }

  /**
   * Setter for <code>workentry_schema.tw_worklog.pause_time</code>.
   */
  def setPauseTime(value : Integer) : Unit = {
    set(4, value)
  }

  /**
   * Getter for <code>workentry_schema.tw_worklog.pause_time</code>.
   */
  def getPauseTime : Integer = {
    val r = get(4)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  /**
   * Setter for <code>workentry_schema.tw_worklog.notes</code>.
   */
  def setNotes(value : String) : Unit = {
    set(5, value)
  }

  /**
   * Getter for <code>workentry_schema.tw_worklog.notes</code>.
   */
  def getNotes : String = {
    val r = get(5)
    if (r == null) null else r.asInstanceOf[String]
  }

  /**
   * Setter for <code>workentry_schema.tw_worklog.editing_reason</code>.
   */
  def setEditingReason(value : String) : Unit = {
    set(6, value)
  }

  /**
   * Getter for <code>workentry_schema.tw_worklog.editing_reason</code>.
   */
  def getEditingReason : String = {
    val r = get(6)
    if (r == null) null else r.asInstanceOf[String]
  }

  /**
   * Setter for <code>workentry_schema.tw_worklog.update_by</code>.
   */
  def setUpdateBy(value : Integer) : Unit = {
    set(7, value)
  }

  /**
   * Getter for <code>workentry_schema.tw_worklog.update_by</code>.
   */
  def getUpdateBy : Integer = {
    val r = get(7)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  /**
   * Setter for <code>workentry_schema.tw_worklog.created</code>.
   */
  def setCreated(value : LocalDateTime) : Unit = {
    set(8, value)
  }

  /**
   * Getter for <code>workentry_schema.tw_worklog.created</code>.
   */
  def getCreated : LocalDateTime = {
    val r = get(8)
    if (r == null) null else r.asInstanceOf[LocalDateTime]
  }

  /**
   * Setter for <code>workentry_schema.tw_worklog.modified</code>.
   */
  def setModified(value : LocalDateTime) : Unit = {
    set(9, value)
  }

  /**
   * Getter for <code>workentry_schema.tw_worklog.modified</code>.
   */
  def getModified : LocalDateTime = {
    val r = get(9)
    if (r == null) null else r.asInstanceOf[LocalDateTime]
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------
  override def key : Record1[Integer] = {
    return super.key.asInstanceOf[ Record1[Integer] ]
  }

  // -------------------------------------------------------------------------
  // Record10 type implementation
  // -------------------------------------------------------------------------

  override def fieldsRow : Row10[Integer, Integer, LocalDate, LocalDate, Integer, String, String, Integer, LocalDateTime, LocalDateTime] = {
    super.fieldsRow.asInstanceOf[ Row10[Integer, Integer, LocalDate, LocalDate, Integer, String, String, Integer, LocalDateTime, LocalDateTime] ]
  }

  override def valuesRow : Row10[Integer, Integer, LocalDate, LocalDate, Integer, String, String, Integer, LocalDateTime, LocalDateTime] = {
    super.valuesRow.asInstanceOf[ Row10[Integer, Integer, LocalDate, LocalDate, Integer, String, String, Integer, LocalDateTime, LocalDateTime] ]
  }
  override def field1 : Field[Integer] = TwWorklog.TW_WORKLOG.ID
  override def field2 : Field[Integer] = TwWorklog.TW_WORKLOG.USER_ID
  override def field3 : Field[LocalDate] = TwWorklog.TW_WORKLOG.START_DATE
  override def field4 : Field[LocalDate] = TwWorklog.TW_WORKLOG.END_DATE
  override def field5 : Field[Integer] = TwWorklog.TW_WORKLOG.PAUSE_TIME
  override def field6 : Field[String] = TwWorklog.TW_WORKLOG.NOTES
  override def field7 : Field[String] = TwWorklog.TW_WORKLOG.EDITING_REASON
  override def field8 : Field[Integer] = TwWorklog.TW_WORKLOG.UPDATE_BY
  override def field9 : Field[LocalDateTime] = TwWorklog.TW_WORKLOG.CREATED
  override def field10 : Field[LocalDateTime] = TwWorklog.TW_WORKLOG.MODIFIED
  override def value1 : Integer = getId
  override def value2 : Integer = getUserId
  override def value3 : LocalDate = getStartDate
  override def value4 : LocalDate = getEndDate
  override def value5 : Integer = getPauseTime
  override def value6 : String = getNotes
  override def value7 : String = getEditingReason
  override def value8 : Integer = getUpdateBy
  override def value9 : LocalDateTime = getCreated
  override def value10 : LocalDateTime = getModified

  override def value1(value : Integer) : TwWorklogRecord = {
    setId(value)
    this
  }

  override def value2(value : Integer) : TwWorklogRecord = {
    setUserId(value)
    this
  }

  override def value3(value : LocalDate) : TwWorklogRecord = {
    setStartDate(value)
    this
  }

  override def value4(value : LocalDate) : TwWorklogRecord = {
    setEndDate(value)
    this
  }

  override def value5(value : Integer) : TwWorklogRecord = {
    setPauseTime(value)
    this
  }

  override def value6(value : String) : TwWorklogRecord = {
    setNotes(value)
    this
  }

  override def value7(value : String) : TwWorklogRecord = {
    setEditingReason(value)
    this
  }

  override def value8(value : Integer) : TwWorklogRecord = {
    setUpdateBy(value)
    this
  }

  override def value9(value : LocalDateTime) : TwWorklogRecord = {
    setCreated(value)
    this
  }

  override def value10(value : LocalDateTime) : TwWorklogRecord = {
    setModified(value)
    this
  }

  override def values(value1 : Integer, value2 : Integer, value3 : LocalDate, value4 : LocalDate, value5 : Integer, value6 : String, value7 : String, value8 : Integer, value9 : LocalDateTime, value10 : LocalDateTime) : TwWorklogRecord = {
    this.value1(value1)
    this.value2(value2)
    this.value3(value3)
    this.value4(value4)
    this.value5(value5)
    this.value6(value6)
    this.value7(value7)
    this.value8(value8)
    this.value9(value9)
    this.value10(value10)
    this
  }

  /**
   * Create a detached, initialised TwWorklogRecord
   */
  def this(id : Integer, userId : Integer, startDate : LocalDate, endDate : LocalDate, pauseTime : Integer, notes : String, editingReason : String, updateBy : Integer, created : LocalDateTime, modified : LocalDateTime) = {
    this()

    set(0, id)
    set(1, userId)
    set(2, startDate)
    set(3, endDate)
    set(4, pauseTime)
    set(5, notes)
    set(6, editingReason)
    set(7, updateBy)
    set(8, created)
    set(9, modified)
  }
}
