/**
 * This class is generated by jOOQ
 */
package models.jooq.tables.daos


import java.lang.Integer
import java.lang.String
import java.time.LocalDateTime
import java.util.List

import javax.annotation.Generated

import models.jooq.tables.TmRole
import models.jooq.tables.records.TmRoleRecord

import org.jooq.Configuration
import org.jooq.impl.DAOImpl

import scala.Array


/**
 * This class is generated by jOOQ.
 */
@Generated(
  value = Array(
    "http://www.jooq.org",
    "jOOQ version:3.8.6"
  ),
  comments = "This class is generated by jOOQ"
)
class TmRoleDao(configuration : Configuration) extends DAOImpl[TmRoleRecord, models.pojos.TmRole, Integer](TmRole.TM_ROLE, classOf[models.pojos.TmRole], configuration) {

  /**
   * Create a new TmRoleDao without any configuration
   */
  def this() = {
    this(null)
  }

  override protected def getId(o : models.pojos.TmRole) : Integer = {
    o.getId
  }

  /**
   * Fetch records that have <code>id IN (values)</code>
   */
  def fetchById(values : Integer*) : List[models.pojos.TmRole] = {
    fetch(TmRole.TM_ROLE.ID, values:_*)
  }

  /**
   * Fetch a unique record that has <code>id = value</code>
   */
  def fetchOneById(value : Integer) : models.pojos.TmRole = {
    fetchOne(TmRole.TM_ROLE.ID, value)
  }

  /**
   * Fetch records that have <code>name IN (values)</code>
   */
  def fetchByName(values : String*) : List[models.pojos.TmRole] = {
    fetch(TmRole.TM_ROLE.NAME, values:_*)
  }

  /**
   * Fetch a unique record that has <code>name = value</code>
   */
  def fetchOneByName(value : String) : models.pojos.TmRole = {
    fetchOne(TmRole.TM_ROLE.NAME, value)
  }

  /**
   * Fetch records that have <code>created IN (values)</code>
   */
  def fetchByCreated(values : LocalDateTime*) : List[models.pojos.TmRole] = {
    fetch(TmRole.TM_ROLE.CREATED, values:_*)
  }

  /**
   * Fetch records that have <code>modified IN (values)</code>
   */
  def fetchByModified(values : LocalDateTime*) : List[models.pojos.TmRole] = {
    fetch(TmRole.TM_ROLE.MODIFIED, values:_*)
  }
}
