/**
 * This class is generated by jOOQ
 */
package models.jooq.tables.daos


import java.lang.Integer
import java.lang.String
import java.time.LocalDateTime
import java.util.List

import javax.annotation.Generated

import models.jooq.tables.TwNews
import models.jooq.tables.records.TwNewsRecord

import org.jooq.Configuration
import org.jooq.impl.DAOImpl

import scala.Array


/**
 * This class is generated by jOOQ.
 */
@Generated(
  value = Array(
    "http://www.jooq.org",
    "jOOQ version:3.8.6"
  ),
  comments = "This class is generated by jOOQ"
)
class TwNewsDao(configuration : Configuration) extends DAOImpl[TwNewsRecord, models.pojos.TwNews, Integer](TwNews.TW_NEWS, classOf[models.pojos.TwNews], configuration) {

  /**
   * Create a new TwNewsDao without any configuration
   */
  def this() = {
    this(null)
  }

  override protected def getId(o : models.pojos.TwNews) : Integer = {
    o.getId
  }

  /**
   * Fetch records that have <code>id IN (values)</code>
   */
  def fetchById(values : Integer*) : List[models.pojos.TwNews] = {
    fetch(TwNews.TW_NEWS.ID, values:_*)
  }

  /**
   * Fetch a unique record that has <code>id = value</code>
   */
  def fetchOneById(value : Integer) : models.pojos.TwNews = {
    fetchOne(TwNews.TW_NEWS.ID, value)
  }

  /**
   * Fetch records that have <code>title IN (values)</code>
   */
  def fetchByTitle(values : String*) : List[models.pojos.TwNews] = {
    fetch(TwNews.TW_NEWS.TITLE, values:_*)
  }

  /**
   * Fetch records that have <code>body IN (values)</code>
   */
  def fetchByBody(values : String*) : List[models.pojos.TwNews] = {
    fetch(TwNews.TW_NEWS.BODY, values:_*)
  }

  /**
   * Fetch records that have <code>author_id IN (values)</code>
   */
  def fetchByAuthorId(values : Integer*) : List[models.pojos.TwNews] = {
    fetch(TwNews.TW_NEWS.AUTHOR_ID, values:_*)
  }

  /**
   * Fetch records that have <code>created IN (values)</code>
   */
  def fetchByCreated(values : LocalDateTime*) : List[models.pojos.TwNews] = {
    fetch(TwNews.TW_NEWS.CREATED, values:_*)
  }

  /**
   * Fetch records that have <code>modified IN (values)</code>
   */
  def fetchByModified(values : LocalDateTime*) : List[models.pojos.TwNews] = {
    fetch(TwNews.TW_NEWS.MODIFIED, values:_*)
  }
}
