/*
 * This file is generated by jOOQ.
*/
package models.jooq.tables.daos


import java.lang.Integer
import java.time.LocalDateTime
import java.util.List

import javax.annotation.Generated

import models.jooq.tables.TwUserRole
import models.jooq.tables.records.TwUserRoleRecord

import org.jooq.Configuration
import org.jooq.impl.DAOImpl

import scala.Array


/**
 * This class is generated by jOOQ.
 */
@Generated(
  value = Array(
    "http://www.jooq.org",
    "jOOQ version:3.9.1"
  ),
  comments = "This class is generated by jOOQ"
)
class TwUserRoleDao(configuration : Configuration) extends DAOImpl[TwUserRoleRecord, models.pojos.TwUserRole, Integer](TwUserRole.TW_USER_ROLE, classOf[models.pojos.TwUserRole], configuration) {

  /**
   * Create a new TwUserRoleDao without any configuration
   */
  def this() = {
    this(null)
  }

  override protected def getId(o : models.pojos.TwUserRole) : Integer = {
    o.getId
  }

  /**
   * Fetch records that have <code>id IN (values)</code>
   */
  def fetchById(values : Integer*) : List[models.pojos.TwUserRole] = {
    fetch(TwUserRole.TW_USER_ROLE.ID, values:_*)
  }

  /**
   * Fetch a unique record that has <code>id = value</code>
   */
  def fetchOneById(value : Integer) : models.pojos.TwUserRole = {
    fetchOne(TwUserRole.TW_USER_ROLE.ID, value)
  }

  /**
   * Fetch records that have <code>user_id IN (values)</code>
   */
  def fetchByUserId(values : Integer*) : List[models.pojos.TwUserRole] = {
    fetch(TwUserRole.TW_USER_ROLE.USER_ID, values:_*)
  }

  /**
   * Fetch records that have <code>role_id IN (values)</code>
   */
  def fetchByRoleId(values : Integer*) : List[models.pojos.TwUserRole] = {
    fetch(TwUserRole.TW_USER_ROLE.ROLE_ID, values:_*)
  }

  /**
   * Fetch records that have <code>created IN (values)</code>
   */
  def fetchByCreated(values : LocalDateTime*) : List[models.pojos.TwUserRole] = {
    fetch(TwUserRole.TW_USER_ROLE.CREATED, values:_*)
  }

  /**
   * Fetch records that have <code>modified IN (values)</code>
   */
  def fetchByModified(values : LocalDateTime*) : List[models.pojos.TwUserRole] = {
    fetch(TwUserRole.TW_USER_ROLE.MODIFIED, values:_*)
  }
}
