/*
 * This file is generated by jOOQ.
*/
package models.jooq.tables.daos


import java.lang.Integer
import java.lang.String
import java.time.LocalDate
import java.time.LocalDateTime
import java.util.List

import javax.annotation.Generated

import models.jooq.tables.TwWorklog
import models.jooq.tables.records.TwWorklogRecord

import org.jooq.Configuration
import org.jooq.impl.DAOImpl

import scala.Array


/**
 * This class is generated by jOOQ.
 */
@Generated(
  value = Array(
    "http://www.jooq.org",
    "jOOQ version:3.9.1"
  ),
  comments = "This class is generated by jOOQ"
)
class TwWorklogDao(configuration : Configuration) extends DAOImpl[TwWorklogRecord, models.pojos.TwWorklog, Integer](TwWorklog.TW_WORKLOG, classOf[models.pojos.TwWorklog], configuration) {

  /**
   * Create a new TwWorklogDao without any configuration
   */
  def this() = {
    this(null)
  }

  override protected def getId(o : models.pojos.TwWorklog) : Integer = {
    o.getId
  }

  /**
   * Fetch records that have <code>id IN (values)</code>
   */
  def fetchById(values : Integer*) : List[models.pojos.TwWorklog] = {
    fetch(TwWorklog.TW_WORKLOG.ID, values:_*)
  }

  /**
   * Fetch a unique record that has <code>id = value</code>
   */
  def fetchOneById(value : Integer) : models.pojos.TwWorklog = {
    fetchOne(TwWorklog.TW_WORKLOG.ID, value)
  }

  /**
   * Fetch records that have <code>user_id IN (values)</code>
   */
  def fetchByUserId(values : Integer*) : List[models.pojos.TwWorklog] = {
    fetch(TwWorklog.TW_WORKLOG.USER_ID, values:_*)
  }

  /**
   * Fetch records that have <code>start_date IN (values)</code>
   */
  def fetchByStartDate(values : LocalDate*) : List[models.pojos.TwWorklog] = {
    fetch(TwWorklog.TW_WORKLOG.START_DATE, values:_*)
  }

  /**
   * Fetch records that have <code>end_date IN (values)</code>
   */
  def fetchByEndDate(values : LocalDate*) : List[models.pojos.TwWorklog] = {
    fetch(TwWorklog.TW_WORKLOG.END_DATE, values:_*)
  }

  /**
   * Fetch records that have <code>pause_time IN (values)</code>
   */
  def fetchByPauseTime(values : Integer*) : List[models.pojos.TwWorklog] = {
    fetch(TwWorklog.TW_WORKLOG.PAUSE_TIME, values:_*)
  }

  /**
   * Fetch records that have <code>notes IN (values)</code>
   */
  def fetchByNotes(values : String*) : List[models.pojos.TwWorklog] = {
    fetch(TwWorklog.TW_WORKLOG.NOTES, values:_*)
  }

  /**
   * Fetch records that have <code>editing_reason IN (values)</code>
   */
  def fetchByEditingReason(values : String*) : List[models.pojos.TwWorklog] = {
    fetch(TwWorklog.TW_WORKLOG.EDITING_REASON, values:_*)
  }

  /**
   * Fetch records that have <code>update_by IN (values)</code>
   */
  def fetchByUpdateBy(values : Integer*) : List[models.pojos.TwWorklog] = {
    fetch(TwWorklog.TW_WORKLOG.UPDATE_BY, values:_*)
  }

  /**
   * Fetch records that have <code>created IN (values)</code>
   */
  def fetchByCreated(values : LocalDateTime*) : List[models.pojos.TwWorklog] = {
    fetch(TwWorklog.TW_WORKLOG.CREATED, values:_*)
  }

  /**
   * Fetch records that have <code>modified IN (values)</code>
   */
  def fetchByModified(values : LocalDateTime*) : List[models.pojos.TwWorklog] = {
    fetch(TwWorklog.TW_WORKLOG.MODIFIED, values:_*)
  }
}
