/**
 * This class is generated by jOOQ
 */
package models.jooq.tables.daos


import java.lang.Integer
import java.math.BigDecimal
import java.time.LocalDateTime
import java.util.List

import javax.annotation.Generated

import models.jooq.tables.TwYearlyBalance
import models.jooq.tables.records.TwYearlyBalanceRecord

import org.jooq.Configuration
import org.jooq.impl.DAOImpl

import scala.Array


/**
 * This class is generated by jOOQ.
 */
@Generated(
  value = Array(
    "http://www.jooq.org",
    "jOOQ version:3.8.6"
  ),
  comments = "This class is generated by jOOQ"
)
class TwYearlyBalanceDao(configuration : Configuration) extends DAOImpl[TwYearlyBalanceRecord, models.pojos.TwYearlyBalance, Integer](TwYearlyBalance.TW_YEARLY_BALANCE, classOf[models.pojos.TwYearlyBalance], configuration) {

  /**
   * Create a new TwYearlyBalanceDao without any configuration
   */
  def this() = {
    this(null)
  }

  override protected def getId(o : models.pojos.TwYearlyBalance) : Integer = {
    o.getId
  }

  /**
   * Fetch records that have <code>id IN (values)</code>
   */
  def fetchById(values : Integer*) : List[models.pojos.TwYearlyBalance] = {
    fetch(TwYearlyBalance.TW_YEARLY_BALANCE.ID, values:_*)
  }

  /**
   * Fetch a unique record that has <code>id = value</code>
   */
  def fetchOneById(value : Integer) : models.pojos.TwYearlyBalance = {
    fetchOne(TwYearlyBalance.TW_YEARLY_BALANCE.ID, value)
  }

  /**
   * Fetch records that have <code>user_id IN (values)</code>
   */
  def fetchByUserId(values : Integer*) : List[models.pojos.TwYearlyBalance] = {
    fetch(TwYearlyBalance.TW_YEARLY_BALANCE.USER_ID, values:_*)
  }

  /**
   * Fetch records that have <code>year IN (values)</code>
   */
  def fetchByYear(values : Integer*) : List[models.pojos.TwYearlyBalance] = {
    fetch(TwYearlyBalance.TW_YEARLY_BALANCE.YEAR, values:_*)
  }

  /**
   * Fetch records that have <code>hour_balance IN (values)</code>
   */
  def fetchByHourBalance(values : BigDecimal*) : List[models.pojos.TwYearlyBalance] = {
    fetch(TwYearlyBalance.TW_YEARLY_BALANCE.HOUR_BALANCE, values:_*)
  }

  /**
   * Fetch records that have <code>vacation_balance IN (values)</code>
   */
  def fetchByVacationBalance(values : BigDecimal*) : List[models.pojos.TwYearlyBalance] = {
    fetch(TwYearlyBalance.TW_YEARLY_BALANCE.VACATION_BALANCE, values:_*)
  }

  /**
   * Fetch records that have <code>created IN (values)</code>
   */
  def fetchByCreated(values : LocalDateTime*) : List[models.pojos.TwYearlyBalance] = {
    fetch(TwYearlyBalance.TW_YEARLY_BALANCE.CREATED, values:_*)
  }

  /**
   * Fetch records that have <code>modified IN (values)</code>
   */
  def fetchByModified(values : LocalDateTime*) : List[models.pojos.TwYearlyBalance] = {
    fetch(TwYearlyBalance.TW_YEARLY_BALANCE.MODIFIED, values:_*)
  }
}
